name: Android CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 18
      uses: actions/setup-java@v1
      with:
          java-version: 18
    - name: create keystore.properties
      env:
        KEYSTORE: ${{ secrets.KEYSTORE }}
      run: echo "$KEYSTORE" > ./keystore.properties
    - name: create secret.properties
      env:
        SECRET: ${{ secrets.SECRET }}
      run: echo "$SECRET" > ./secret.properties
    - name: create google_service.json
      env:
        GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
      run: echo "$GOOGLE_SERVICE_JSON" > ./androidApp/google-services.json
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    - name: Clean
      run: ./gradlew clean
    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace

